name: Clean Code

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  clean:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0
      - name: Clean Code Files
        run: |
          find . \( -name "*.md" -o -name "*.json" -o -name "*.js" -o -name "*.css" -o -name "*.java" \) -print0 | while IFS= read -r -d $'\0' file; do
            sed -i -e '/^$/N;/^\n$/D' -e 's/[[:space:]]*$//' "$file"
          done
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Cleaned up code files"
          file_pattern: "*.md *.json *.js *.css *.java"

