name: Cross-Platform Echo

on:
  push:
    paths: # Trigger only when files are updated
      - '**' # Matches any file or directory in the repository

jobs:
  echo-message:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest] # Run on both Ubuntu and Windows
    runs-on: ${{ matrix.os }}
    steps:
      - name: Echo message
        if: matrix.os == 'ubuntu-latest' # Condition for Ubuntu
        run: echo "Hello from Ubuntu!"
      - name: Echo message
        if: matrix.os == 'windows-latest' # Condition for Windows
        run: echo "Hello from Windows!"
