name: Format Code





on: [push]

jobs:
  format-code:
    runs-on: ubuntu-latest
    steps:
        - name: Format code
          run: |
            fmt -s -w 80 $(find . -type f -name "**/*.*")
            find . -type f -name "**/*.*" -exec sed -i '/^$/d' {} +




