name: Remove Consecutive Blank Lines

on:
  workflow_dispatch:

jobs:
  remove-blank-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code # Added name here
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Remove consecutive blank lines
        run: |
          find . -type f \( -name "*.js" -o -name "*.json" -o -name "*.md" -o -name "*.yml" -o -name "*.yaml" -o -name "*.markdown" -o -name "*.css" -o -name "*.txt" \) -exec sed -i '/^\s*$/N;/^\s*$/D' {} +
          git status
          git diff

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Remove consecutive blank lines"
          file_pattern: ./**/*.md

          # pre_commit_command: "echo 'Files changed:' && git status"
