name: Remove Consecutive Blank Lines

on:
  push:
    paths:
      - '**' 

jobs:
  remove-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Remove Blank Lines
        run: |
          find . -type f \( -name "*.c" -o -name "*.cpp" -o -name "*.cs" -o -name "*.css" -o -name "*.html" -o -name "*.java" -o -name "*.js" -o -name "*.json" -o -name "*.md" -o -name "*.markdown" -o -name "*.py" -o -name "*.xml" -o -name "*.yaml" -o -name "*.yml" \) -not -path "./node_modules/*" -not -path "./.github/workflows/*" -exec bash -c 'if git ls-files {} >/dev/null 2>&1; then sed -i "/^\s*$/N;/^\s*$/D" {}; fi' \;

      - name: Add Changes to Git
        run: git add --all

      - name: Configure Git User and Email
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git commit -m "Remove consecutive blank lines"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
