name: Remove Consecutive Blank Lines

on:
  workflow_dispatch:

jobs:
  remove-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Remove Blank Lines
        run: |
          find . -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.js" -o -name "*.json" -o -name "*.css" \) -exec sed -i '/^\s*$/N;/^\s*$/D' {} +

      - name: Debug Print Before
        run: cat README.md

      - name: Debug Print After
        run: |
            find . -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.js" -o -name "*.json" -o -name "*.css" \) -exec sed '/^\s*$/N;/^\s*$/D' {} \; # Print output without -i to check
            cat README.md # Print the file content after sed command

      - name: Git Status Before Add
        run: git status


      - name: Add Changes to Git
        run: git add .

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Remove consecutive blank lines"
          file_pattern: ./**/*.{md,markdown,js,json,css}
