name: Remove Consecutive Blank Lines

on:
  workflow_dispatch:

jobs:
  remove-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          persist-credentials: false  # Use the workflow triggerer's token

      - name: Remove Blank Lines
        run: |
          find . -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.js" -o -name "*.json" -o -name "*.css" \) -exec sed -i '/^\s*$/N;/^\s*$/D' {} +

      - name: Configure Git User and Email  # IMPORTANT
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git add .
          git commit -m "Remove consecutive blank lines"

      - name: Push Changes  # Push the changes back
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
