name: Remove Consecutive Blank Lines

on:
  push:
    paths:
      - '**' 

jobs:
  remove-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}
          persist-credentials: false

      - name: Remove Blank Lines
        run: |
          file_patterns=( "*.c" "*.cpp" "*.cs" "*.css" "*.html" "*.java" "*.js" "*.json" "*.md" "*.markdown" "*.py" "*.xml" "*.yaml" "*.yml" )
          find . -type f \( -name "${file_patterns[@]}" \) -not -path "./node_modules/*" -not -path "./.github/workflows/*" -print0 | xargs -0 -t bash -c 'if git ls-files "$1" >/dev/null 2>&1; then sed -i "/^\s*$/N;/^\s*$/D" "$1"; fi' -- {}

      - name: Add Changes to Git
        run: git add --all

      - name: Configure Git User and Email
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Commit Changes
        run: |
          git commit -m "Remove consecutive blank lines in: $(git diff --name-only --cached)"

      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
