name: Remove Consecutive Blank Lines

on: workflow_dispatch

jobs:
  remove-lines:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: List Files
        run: ls -al

      - name: Print README.md Before
        run: cat README.md

      - name: Find Files
        id: blank-lines
        run: |
          echo "::set-output name=files_found::$(find . -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.js" -o -name "*.json" -o -name "*.css" \))"

      - name: Warning files found
        if: steps.blank-lines.outputs.files_found == ''
        run: |
          echo "::warning::No files found to process"

      - name: Files found
        if: steps.blank-lines.outputs.files_found != ''
        run: |
            echo "::notice::Files found to process: ${{ steps.blank-lines.outputs.files_found }}"

      - name: Remove Blank Lines
        run: |
          find . -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.js" -o -name "*.json" -o -name "*.css" \) -print0 | xargs -0 -t sed -i '/^\s*$/N;/^\s*$/D'


      - name: Dry Run sed
        run: |
           find . -type f \( -name "*.md" -o -name "*.markdown" -o -name "*.js" -o -name "*.json" -o -name "*.css" \) -exec sed '/^\s*$/N;/^\s*$/D' {} \;

      - name: Print README.md After
        run: cat README.md

      - name: Git Status Before Add
        run: git status

      - name: Add Changes to Git
        run: git add --all

      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Remove consecutive blank lines"
          file_pattern: ./**/*.{md,markdown,js,json,css}

